Vagrant.configure("2") do |config|
  config.vm.box = "ptrampert/ubuntu-focal"
  config.vm.box_url = "https://packages.ptrampert.com/repository/vagrant/ubuntu-focal.tar.gz"

  config.vm.provider "hyperv" do |hyperv|
    hyperv.cpus = 4
    hyperv.memory = 4096
  end

  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
  end
end
